app/models.py
from datetime import datetime

from . import db 


class User(db.Model):
    """SQLALchemy model to represent users table.
    
    :param user_id: unique user identifier.
    :param username: user nick name.
    """
    __tablename__ = "users"
    
    user_id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64))
    
    messages = db.relationship("Message", backref="author", cascade="all,delete", lazy="dynamic")
    
    def __repr__(self):
        return f"<User {self.username}>"
    
    
class Room(db.Model):
    """SQLALchemy model to represent rooms table.
    
    :param room_id: unique room identifier.
    :param room_name: room name.
    """
    __tablename__ = "rooms"
    
    room_id = db.Column(db.Integer, primary_key=True)
    room_name = db.Column(db.String(64), nullable=False, unique=True)
    
    messages = db.relationship("Message", backref="room", cascade="all,delete", lazy="dynamic")
    
    def __repr__(self):
        return f"<Room {self.room_name}>"
    
    
class Message(db.Model):
    """SQLALchemy model to represent messages table.
    
    :param message_id: unique user identifier.
    :param text: message body.
    :param timestamp: date and time message was sent.
    :param author_id: message publisher id.
    :param room_id: room where message was published.
    """
    __tablename__ = "messages"
    
    message_id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey("users.user_id"))
    room_id = db.Column(db.Integer, db.ForeignKey("rooms.room_id"))
    
    def get_timestamp(self):
        """Convert message timestamp to string repr."""
        return self.timestamp.strftime("%m.%d.%Y, %H:%M")
    
    def __repr__(self):
        return f"<Message {self.message_id}>"
    

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """Login Page form.
    
    :param username: user nickname field.
    :param room: room to enter field.
    :param submit: submit button.
    """
    username = StringField("Username", validators=[DataRequired()])
    room = StringField("Room", validators=[DataRequired()])
    submit = SubmitField("Join Room")

app/__init__.py
import os

from flask import Flask 
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_socketio import SocketIO
from flask_sqlalchemy import SQLAlchemy

from .utils import generate_basedir

bootstrap = Bootstrap()
db = SQLAlchemy()
moment = Moment()
sio = SocketIO()


def create_app(debug=False):
    """Application factory.
    
    :param debug: run application with debug mode.
    """
    app = Flask(__name__)
    app.secret_key = "8cwyja9fql"
    app.debug = debug
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///" + os.path.join(generate_basedir(), "database.sqlite")
    
    bootstrap.init_app(app)
    db.init_app(app)
    moment.init_app(app)
    sio.init_app(app)
    
    from .views import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    return app 

app/views.py
from flask import Blueprint, redirect, render_template, session, url_for

from . import db, events
from .decorators import login_required
from .forms import LoginForm
from .models import User, Room

main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
def index():
    """Index page route handler.
    
    :GET landing page: "main.index".
    :POST login user and redirect to "main.chat".
    """
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None:
            user = User(username=form.username.data)
            db.session.add(user)
            db.session.commit()
            
        room = Room.query.filter_by(room_name=form.room.data).first()
        if room is None:
            room = Room(room_name=form.room.data)
            db.session.add(room)
            db.session.commit()
            
        session["user"] = user.user_id 
        session["room"] = room.room_id
        return redirect(url_for("main.chat"))
    rooms = Room.query.all()
    return render_template("index.html", form=form, rooms=rooms)


@main.route("/chat")
@login_required
def chat():
    """Chat page route handler.
    
    :GET landing page: "main.chat".
    """
    username = User.query.get(session.get("user")).username
    
    room = Room.query.get(session.get("room"))
    messages = room.messages
    room_name = room.room_name
    return render_template("chat.html", username=username, messages=messages,
                           room_name=room_name)


@main.route("/home")
@login_required
def home():
    """Home page route handler with logout function.
    
    :GET reset session credentials and redirect to "main.index".
    """
    session["user"] = None 
    return redirect(url_for("main.index"))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{% endblock %}

{% block head %}
    {{super()}}
    <link rel="stylesheet" href="{{url_for('static', filename='styles/chat.css')}}">
{% endblock %}


{% block content %}
    {{super()}}
    <div class="container">
        {% block page_content %}
        {% endblock %}
    </div>
{% endblock %}

{% block scripts %}
{{super()}}
{{moment.include_moment()}}
{{moment.lang('EN')}}
{% endblock %}

app/templates/chat.html
{% extends "base.html" %}

{% block title %}Room - {{room_name}}{% endblock %}

{% block page_content %}
    <div class="page-header">
        <div class="header-content">
            <div class="col-md-8"><h1>Chat of {{room_name}} room.</h1></div>
            <div class="col-md-4"><a class="btn btn-primary pull-right" href="{{url_for('main.home')}}">Back home.</a></div>
        </div>
    </div>
    
    
        <div class="form-group">
            <textarea class="form-control" id="chat-history" rows="8" readonly>{% if messages[0] %}{% for message in messages %}{{message.get_timestamp()}} {{message.author.username}}: {{message.text}} &#10;{% endfor %}{% endif %}</textarea> <br>
            <input type="text" class="form-control" id="user-message" placeholder="Type your message here..."> <br>
            <button class="btn btn-primary" id="send-message">Send</button>
        </div>
    
{% endblock %}

{% block scripts %}
    {{super()}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.5.0/socket.io.min.js"></script>
    <script src="{{url_for('static', filename='js/socketio.js')}}"></script>
    <script>const username = `{{username}}`</script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}SocketIO Home{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1>SocketIO Home.</h1>
    </div>
    {{wtf.quick_form(form, button_map={'submit': 'primary'})}}

    {% if rooms[0] %}
    <h1>Rooms available:</h1>
        {% for room in rooms %}
            <h2>{{room.room_name}}</h2>
        {% endfor %}
    {% endif %}
{% endblock %}